# Change these first
owner: animatedcreativity # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: Animated Creativity
    url: https://animatedcreativity.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.ylo.one
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Up
  introTitle: "All public services by Animated Creativity."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Animated Creativity
      href: https://animatedcreativity.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
